apiVersion: v1
kind: Service
metadata:
  labels:
    app: { { .Values.appName } }
  name: { { .Values.appName } }
  namespace: { { .Values.namespace } }
spec:
  type: ClusterIP
  ports:
    - port: 8071
      targetPort: 8071
  selector:
    #Must match Deployment selector under matchLabels:
    app: { { .Values.appName } }
